USE [master]
GO

/****** Object:  Database [PRODUCTION_DATA]    Script Date: 3/25/2015 2:49:52 PM ******/
CREATE DATABASE [PRODUCTION_DATA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRODUCTION_DATA', FILENAME = N'D:\SQLDATA\PRODUCTION_DATA.mdf' , SIZE = 94208KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PRODUCTION_DATA_log', FILENAME = N'L:\SQLLOGS\PRODUCTION_DATA_log.ldf' , SIZE = 1055744KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

ALTER DATABASE [PRODUCTION_DATA] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRODUCTION_DATA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRODUCTION_DATA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRODUCTION_DATA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRODUCTION_DATA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRODUCTION_DATA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [PRODUCTION_DATA] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [PRODUCTION_DATA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRODUCTION_DATA] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PRODUCTION_DATA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET RECOVERY FULL 
GO

ALTER DATABASE [PRODUCTION_DATA] SET  MULTI_USER 
GO

ALTER DATABASE [PRODUCTION_DATA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRODUCTION_DATA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRODUCTION_DATA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRODUCTION_DATA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PRODUCTION_DATA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRODUCTION_DATA] SET  READ_WRITE 
GO


